modLoader="javafml" #mandatory
loaderVersion="[45,)" #mandatory
license="All rights reserved"
[[mods]] #mandatory
modId="frv" #mandatory
version="1.20-2.0" #mandatory
displayName="Stellar Conquest" #mandatory
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/the-stellar-conquest" #optional
logoFile="stlconlogo.png" #optional
authors="Feroov" #optional
# (#mandatory)
description='''
Stellar Conquest is a Minecraft mod that offers a thrilling galaxy adventure.Players battle aliens, explore planets by defeating a mothership, and unlocking the pathway to alien dimensions for new challenges and rare resources.'''

[[dependencies.geckolib]]
modId="geckolib"
mandatory=true
versionRange="[1.20)"
ordering="NONE"
side="BOTH"
