modLoader="javafml" #mandatory
loaderVersion="[45,)" #mandatory
license="All rights reserved"
[[mods]] #mandatory
modId="frv" #mandatory
version="1.0-1.19.4" #mandatory
displayName="Stellar Conquest" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/stellar-conquest" #optional
#logoFile="rotmlogo.png" #optional
authors="Feroov" #optional
# (#mandatory)
description='''
Stellar Conquest is a Minecraft mod that takes players on a thrilling adventure across the galaxy,
battling against alien creatures and exploring distant planets. Players must first defeat the alien
mothership to gain access to the alien dimension, where they will face new challenges and discover
 rare resources.'''

[[dependencies.geckolib]]
modId="geckolib"
mandatory=true
versionRange="[1.19.3,1.20)"
ordering="NONE"
side="BOTH"
